### ISSUE TITLE
"Upload image" only working in chrome :  fix it with a new button 

### ISSUE THREAD

**Issue by loikun** [QuirkyCort/ev3dev-sim#11]
The "upload image" only working with google chrome can be fixed by simply moving this option (and the associated  js code)  in a button : 
  
 index.html        
```
          <!-- <option>Upload Image (2362x1143px)...</option> -->
          <option hidden>Custom Image</option>
        </select>
        <button id="uploadMapBtn">Upload Image (2362x1143px)</button>         <!-- the new button -->
        <button id="robotConfiguratorOpen">Configure Robot</button>



    document.getElementById('uploadMapBtn').addEventListener('click', function() {
       var hiddenElement = document.createElement('input');
       hiddenElement.type = 'file';
       hiddenElement.accept = 'image/*';
       console.log(hiddenElement);
       hiddenElement.dispatchEvent(new MouseEvent('click'));
       hiddenElement.addEventListener('change', function(e){
         var reader = new FileReader();
         reader.onload = function() {
           sim.loadBackground(this.result);
           sim.clearObstacles();
           sim.clearObstaclesLayer();
         };
         reader.readAsDataURL(e.target.files[0]);
       });
       var select = document.getElementById('map');
       select.selectedIndex = select.options.length - 1;
      });

```

Tested with safari, firefox.
If I am correct, the issue was that  hiddenElement.dispatchEvent(new MouseEvent('click'));  required a real previous click of the user to be active in the other browser.

On another topic, i will now see if the robot configurator is flexible enough to freely choose the 4 sensor types connected to the robot. 
I may need 3 ultrasonic sensors connected to the ev3 to solve a labyrinth considering an inaccurate odometry. I will issue a pull request, if I have to update the robot configuration code. Best regards

**Comment by QuirkyCort** [comment]
Yeah, for some reason, Firefox doesn't treat the dropdown selection as a user initiated event, but Chrome does. I consider this a bug in Firefox, so I never bothered to fix this before, though I can't be 100% sure since I can't find any documentations on what exactly constitute a user initiated event.

Anyway, I've replaced it with a button as you've suggested. Should work fine on all browsers.

Unfortunately, the 4 sensors are hardcoded. You can't change their types without making substantial changes to the code. It's on the top of my TODO list to make them fully configurable, but I've been too busy to get around to it. If you do manage to get that done, I'll be happy to accept the PR.
