### ISSUE TITLE
Browser freezes when no sensor values are read

### ISSUE THREAD

**Issue by ch515** [QuirkyCort/ev3dev-sim#12]
While testing, I noticed that if you do not use any sensor values in the python program, the browser will completely freeze.  Do you happen to know of any workarounds for this?

**Comment by QuirkyCort** [comment]
The browser hangs because every tab runs in a single thread. If the Python interpreter (skulpt) keeps running in a continuous loop without sleeping, it won't release control back to the browser.

In all the sensor reads, I've hidden a small sleep in the library to prevent the hang. If you need to run a loop without any sensor read, you'll need to add in the sleep yourself. Something like a "time.sleep(0.001)" should suffice.

Btw, I've been working on a successor to the simulator. You can find it here. https://gears.aposteriori.com.sg/) Feedback / bug reports / suggestions are appreciated.
